### ISSUE TITLE
Updating the project name.

### ISSUE THREAD

**Issue by prakhart111** [hellodeborahuk/buzzphonics#45]
**Describe the bug**
Project name not updated at some places in README.md and CONTRIBUTING.md

**To Reproduce**
1. Go to README.md and CONTRIBUTING.md
2. See error

**Expected behavior**
Replace 'phonics-sounds' name with the new name of Repository 'buzzphonics'

**Comment by prakhart111** [comment]
@prakhart111

**Comment by hellodeborahuk** [comment]
Links to PR #46
