### ISSUE TITLE
ScoreBoard update request

### ISSUE THREAD

**Issue by prakhart111** [hellodeborahuk/buzzphonics#48]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is Get the score board on top, with a better design.

Ex. I'm always frustrated when I need to go at the bottom of the screen, to view my score.

**Describe the solution you'd like**
Below the good afternoon message, the score board should be placed, with a better, more circular design.

**Describe alternatives you've considered**
I am not sure why the project isn't running on my local machine, I think have some issues on my side, will resolve it, so just creating an issue for this feature request.

**Additional context**
Not yet, but yours project is good, found it on HashNode.

Will be coming up with more feature updates when it runs on mine ;)

Twitter ?
[I am here](https://twitter.com/prakhartandon29)

**Comment by hellodeborahuk** [comment]
Thank you for your idea, Prakhar. The reason it's shaped as a hexagon is to tie in with the branding, like a beehive. For now, I'd like to keep it at the bottom as my daughter likes to have quick access to the games and would rather scroll to see her points. But as more features are added (she wants to be able to do something with her points) this may need to be revisited. Thank you.
